"""empty message

Revision ID: 82af8869797c
Revises: 
Create Date: 2021-08-08 11:56:34.924722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82af8869797c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('cards_created_by_id_fkey', 'cards', type_='foreignkey')
    op.drop_column('cards', 'created_by_id')
    op.drop_column('cards', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('cards', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cards_created_by_id_fkey', 'cards', 'users', ['created_by_id'], ['id'])
    op.drop_column('cards', 'description')
    op.drop_column('cards', 'title')
    # ### end Alembic commands ###
