"""history tables

Revision ID: 87a68738ef04
Revises: 82af8869797c
Create Date: 2021-09-08 13:16:50.606528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a68738ef04'
down_revision = '82af8869797c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('last_change_by_id', sa.Integer(), nullable=False),
    sa.Column('last_change_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['last_change_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_history_list_id'), 'lists_history', ['list_id'], unique=False)
    op.create_table('cards_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('last_change_by_id', sa.Integer(), nullable=True),
    sa.Column('last_change_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_change_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_history_card_id'), 'cards_history', ['card_id'], unique=False)
    op.create_index(op.f('ix_cards_history_list_id'), 'cards_history', ['list_id'], unique=False)
    op.create_index(op.f('ix_board_users_board_id'), 'board_users', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_users_user_id'), 'board_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_users_user_id'), table_name='board_users')
    op.drop_index(op.f('ix_board_users_board_id'), table_name='board_users')
    op.drop_index(op.f('ix_cards_history_list_id'), table_name='cards_history')
    op.drop_index(op.f('ix_cards_history_card_id'), table_name='cards_history')
    op.drop_table('cards_history')
    op.drop_index(op.f('ix_lists_history_list_id'), table_name='lists_history')
    op.drop_table('lists_history')
    # ### end Alembic commands ###
