"""on_delete

Revision ID: c3735e1cde43
Revises: 30d1d46ac185
Create Date: 2021-09-09 08:38:28.257702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3735e1cde43'
down_revision = '30d1d46ac185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
